apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "another-test-vault-approle"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "vaultAppRole"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  roleId: db02de05-fa39-4855-059b-67221c5c2f63
  secretId: 6a174c20-f6de-a53c-74d2-6018fcceff64
# optional fields
  path: approle-jenkins    # defaults to 'approle'
  namespace: team1         # defaults to global vault jenkins configuration
