kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: testing
  name: secret-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
#  https://github.com/jcbsmpsn/gke-rbac-walkthrough/blob/master/create-roles.md